language: python
sudo: required
install:
    - git clone https://github.com/fletcher/MultiMarkdown-5
    - cd MultiMarkdown-5; git checkout develop; ./link_git_modules; ./update_git_modules; make shared; cd build; make; sudo make install;cd ../..
    - python setup.py install
script:
    - echo "Placeholder"